. ".\synbase.ps1"
SynSrc -orignalDir $rootdir -srcDir "HackedTeam/vector-ni" -projectName "HackedTeam/vector-ni" -git "https://github.com/hackedteam/vector-ni.git"
SynSrc -orignalDir $rootdir -srcDir "HackedTeam/rcs-db" -projectName "HackedTeam/rcs-db" -git "https://github.com/hackedteam/rcs-db.git"
SynSrc -orignalDir $rootdir -srcDir "HackedTeam/fuzzer-android" -projectName "HackedTeam/fuzzer-android" -git "https://github.com/hackedteam/fuzzer-android.git"
SynSrc -orignalDir $rootdir -srcDir "HackedTeam/vector-exploit" -projectName "HackedTeam/vector-exploit" -git "https://github.com/hackedteam/vector-exploit.git"
SynSrc -orignalDir $rootdir -srcDir "HackedTeam/test-av2" -projectName "HackedTeam/test-av2" -git "https://github.com/hackedteam/test-av2.git"
SynSrc -orignalDir $rootdir -srcDir "HackedTeam/core-winphone" -projectName "HackedTeam/core-winphone" -git "https://github.com/hackedteam/core-winphone.git"
SynSrc -orignalDir $rootdir -srcDir "HackedTeam/rcs-db-ext" -projectName "HackedTeam/rcs-db-ext" -git "https://github.com/hackedteam/rcs-db-ext.git"
SynSrc -orignalDir $rootdir -srcDir "HackedTeam/core-android-market" -projectName "HackedTeam/core-android-market" -git "https://github.com/hackedteam/core-android-market.git"
SynSrc -orignalDir $rootdir -srcDir "HackedTeam/scout-win" -projectName "HackedTeam/scout-win" -git "https://github.com/hackedteam/scout-win.git"
SynSrc -orignalDir $rootdir -srcDir "HackedTeam/core-android-audiocapture" -projectName "HackedTeam/core-android-audiocapture" -git "https://github.com/hackedteam/core-android-audiocapture.git"
SynSrc -orignalDir $rootdir -srcDir "HackedTeam/vector-edk" -projectName "HackedTeam/vector-edk" -git "https://github.com/hackedteam/vector-edk.git"
SynSrc -orignalDir $rootdir -srcDir "HackedTeam/core-ios" -projectName "HackedTeam/core-ios" -git "https://github.com/hackedteam/core-ios.git"
SynSrc -orignalDir $rootdir -srcDir "HackedTeam/core-blackberry" -projectName "HackedTeam/core-blackberry" -git "https://github.com/hackedteam/core-blackberry.git"
SynSrc -orignalDir $rootdir -srcDir "HackedTeam/core-symbian" -projectName "HackedTeam/core-symbian" -git "https://github.com/hackedteam/core-symbian.git"
SynSrc -orignalDir $rootdir -srcDir "HackedTeam/core-android" -projectName "HackedTeam/core-android" -git "https://github.com/hackedteam/core-android.git"
SynSrc -orignalDir $rootdir -srcDir "HackedTeam/vector-silent" -projectName "HackedTeam/vector-silent" -git "https://github.com/hackedteam/vector-silent.git"
SynSrc -orignalDir $rootdir -srcDir "HackedTeam/core-winmobile" -projectName "HackedTeam/core-winmobile" -git "https://github.com/hackedteam/core-winmobile.git"
SynSrc -orignalDir $rootdir -srcDir "HackedTeam/vector-default" -projectName "HackedTeam/vector-default" -git "https://github.com/hackedteam/vector-default.git"
SynSrc -orignalDir $rootdir -srcDir "HackedTeam/vector-offline2" -projectName "HackedTeam/vector-offline2" -git "https://github.com/hackedteam/vector-offline2.git"
SynSrc -orignalDir $rootdir -srcDir "HackedTeam/test-av" -projectName "HackedTeam/test-av" -git "https://github.com/hackedteam/test-av.git"
SynSrc -orignalDir $rootdir -srcDir "HackedTeam/rcs-console" -projectName "HackedTeam/rcs-console" -git "https://github.com/hackedteam/rcs-console.git"
SynSrc -orignalDir $rootdir -srcDir "HackedTeam/fuzzer-windows" -projectName "HackedTeam/fuzzer-windows" -git "https://github.com/hackedteam/fuzzer-windows.git"
SynSrc -orignalDir $rootdir -srcDir "HackedTeam/core-win32" -projectName "HackedTeam/core-win32" -git "https://github.com/hackedteam/core-win32.git"
SynSrc -orignalDir $rootdir -srcDir "HackedTeam/core-android-native" -projectName "HackedTeam/core-android-native" -git "https://github.com/hackedteam/core-android-native.git"
SynSrc -orignalDir $rootdir -srcDir "HackedTeam/rcs-anonymizer-old" -projectName "HackedTeam/rcs-anonymizer-old" -git "https://github.com/hackedteam/rcs-anonymizer-old.git"
SynSrc -orignalDir $rootdir -srcDir "HackedTeam/poc-x" -projectName "HackedTeam/poc-x" -git "https://github.com/hackedteam/poc-x.git"
SynSrc -orignalDir $rootdir -srcDir "HackedTeam/gitosis-admin" -projectName "HackedTeam/gitosis-admin" -git "https://github.com/hackedteam/gitosis-admin.git"
SynSrc -orignalDir $rootdir -srcDir "HackedTeam/driver-macos" -projectName "HackedTeam/driver-macos" -git "https://github.com/hackedteam/driver-macos.git"
SynSrc -orignalDir $rootdir -srcDir "HackedTeam/vector-dropper" -projectName "HackedTeam/vector-dropper" -git "https://github.com/hackedteam/vector-dropper.git"
SynSrc -orignalDir $rootdir -srcDir "HackedTeam/core-linux" -projectName "HackedTeam/core-linux" -git "https://github.com/hackedteam/core-linux.git"
SynSrc -orignalDir $rootdir -srcDir "HackedTeam/core-macos" -projectName "HackedTeam/core-macos" -git "https://github.com/hackedteam/core-macos.git"
SynSrc -orignalDir $rootdir -srcDir "HackedTeam/rcs-common" -projectName "HackedTeam/rcs-common" -git "https://github.com/hackedteam/rcs-common.git"
SynSrc -orignalDir $rootdir -srcDir "HackedTeam/GeoTrust" -projectName "HackedTeam/GeoTrust" -git "https://github.com/hackedteam/GeoTrust.git"
SynSrc -orignalDir $rootdir -srcDir "HackedTeam/soldier-win" -projectName "HackedTeam/soldier-win" -git "https://github.com/hackedteam/soldier-win.git"
SynSrc -orignalDir $rootdir -srcDir "HackedTeam/rcs-anonymizer" -projectName "HackedTeam/rcs-anonymizer" -git "https://github.com/hackedteam/rcs-anonymizer.git"
SynSrc -orignalDir $rootdir -srcDir "HackedTeam/rcs-collector" -projectName "HackedTeam/rcs-collector" -git "https://github.com/hackedteam/rcs-collector.git"
SynSrc -orignalDir $rootdir -srcDir "HackedTeam/rcs-backdoor" -projectName "HackedTeam/rcs-backdoor" -git "https://github.com/hackedteam/rcs-backdoor.git"
SynSrc -orignalDir $rootdir -srcDir "HackedTeam/vector-applet" -projectName "HackedTeam/vector-applet" -git "https://github.com/hackedteam/vector-applet.git"
SynSrc -orignalDir $rootdir -srcDir "HackedTeam/driver-win32" -projectName "HackedTeam/driver-win32" -git "https://github.com/hackedteam/driver-win32.git"
SynSrc -orignalDir $rootdir -srcDir "HackedTeam/driver-win64" -projectName "HackedTeam/driver-win64" -git "https://github.com/hackedteam/driver-win64.git"
SynSrc -orignalDir $rootdir -srcDir "HackedTeam/vector-offline" -projectName "HackedTeam/vector-offline" -git "https://github.com/hackedteam/vector-offline.git"
SynSrc -orignalDir $rootdir -srcDir "HackedTeam/rcs-console-library" -projectName "HackedTeam/rcs-console-library" -git "https://github.com/hackedteam/rcs-console-library.git"
SynSrc -orignalDir $rootdir -srcDir "HackedTeam/rcs-console-mobile" -projectName "HackedTeam/rcs-console-mobile" -git "https://github.com/hackedteam/rcs-console-mobile.git"
SynSrc -orignalDir $rootdir -srcDir "HackedTeam/core-packer" -projectName "HackedTeam/core-packer" -git "https://github.com/hackedteam/core-packer.git"
SynSrc -orignalDir $rootdir -srcDir "HackedTeam/shshget" -projectName "HackedTeam/shshget" -git "https://github.com/hackedteam/shshget.git"
SynSrc -orignalDir $rootdir -srcDir "HackedTeam/melter" -projectName "HackedTeam/melter" -git "https://github.com/hackedteam/melter.git"
SynSrc -orignalDir $rootdir -srcDir "HackedTeam/libpemelter" -projectName "HackedTeam/libpemelter" -git "https://github.com/hackedteam/libpemelter.git"
SynSrc -orignalDir $rootdir -srcDir "HackedTeam/libmelter" -projectName "HackedTeam/libmelter" -git "https://github.com/hackedteam/libmelter.git"
SynSrc -orignalDir $rootdir -srcDir "HackedTeam/vector-rmi" -projectName "HackedTeam/vector-rmi" -git "https://github.com/hackedteam/vector-rmi.git"
SynSrc -orignalDir $rootdir -srcDir "HackedTeam/vector-recover" -projectName "HackedTeam/vector-recover" -git "https://github.com/hackedteam/vector-recover.git"
SynSrc -orignalDir $rootdir -srcDir "HackedTeam/vector-macos-root" -projectName "HackedTeam/vector-macos-root" -git "https://github.com/hackedteam/vector-macos-root.git"
SynSrc -orignalDir $rootdir -srcDir "HackedTeam/vector-ipa" -projectName "HackedTeam/vector-ipa" -git "https://github.com/hackedteam/vector-ipa.git"
SynSrc -orignalDir $rootdir -srcDir "HackedTeam/core-win64" -projectName "HackedTeam/core-win64" -git "https://github.com/hackedteam/core-win64.git"



#Write-Host -ForegroundColor Green  "全部完成"




