. ".\synbase.ps1"
SynSrc -orignalDir $rootdir -srcDir "ASPNET/BugTracker" -projectName "ASPNET/BugTracker" -git "https://github.com/ASPNET/BugTracker.git"
SynSrc -orignalDir $rootdir -srcDir "ASPNET/Caching" -projectName "ASPNET/Caching" -git "https://github.com/ASPNET/Caching.git"
SynSrc -orignalDir $rootdir -srcDir "ASPNET/Coherence" -projectName "ASPNET/Coherence" -git "https://github.com/ASPNET/Coherence.git"
SynSrc -orignalDir $rootdir -srcDir "ASPNET/Configuration" -projectName "ASPNET/Configuration" -git "https://github.com/ASPNET/Configuration.git"
#SynSrc -orignalDir $rootdir -srcDir "ASPNET/DataCommon" -projectName "ASPNET/DataCommon" -git "https://github.com/ASPNET/DataCommon.git"
SynSrc -orignalDir $rootdir -srcDir "ASPNET/DataCommon.SQLite" -projectName "ASPNET/DataCommon.SQLite" -git "https://github.com/ASPNET/DataCommon.SQLite.git"
SynSrc -orignalDir $rootdir -srcDir "ASPNET/DataProtection" -projectName "ASPNET/DataProtection" -git "https://github.com/ASPNET/DataProtection.git"
SynSrc -orignalDir $rootdir -srcDir "ASPNET/DependencyInjection" -projectName "ASPNET/DependencyInjection" -git "https://github.com/ASPNET/DependencyInjection.git"
SynSrc -orignalDir $rootdir -srcDir "ASPNET/Diagnostics" -projectName "ASPNET/Diagnostics" -git "https://github.com/ASPNET/Diagnostics.git"
SynSrc -orignalDir $rootdir -srcDir "ASPNET/EntityFramework" -projectName "ASPNET/EntityFramework" -git "https://github.com/ASPNET/EntityFramework.git"
SynSrc -orignalDir $rootdir -srcDir "ASPNET/Entropy" -projectName "ASPNET/Entropy" -git "https://github.com/ASPNET/Entropy.git"
SynSrc -orignalDir $rootdir -srcDir "ASPNET/FileSystem" -projectName "ASPNET/FileSystem" -git "https://github.com/ASPNET/FileSystem.git"
SynSrc -orignalDir $rootdir -srcDir "ASPNET/Home" -projectName "ASPNET/Home" -git "https://github.com/ASPNET/Home.git"
SynSrc -orignalDir $rootdir -srcDir "ASPNET/Hosting" -projectName "ASPNET/Hosting" -git "https://github.com/ASPNET/Hosting.git"
SynSrc -orignalDir $rootdir -srcDir "ASPNET/HttpAbstractions" -projectName "ASPNET/HttpAbstractions" -git "https://github.com/ASPNET/HttpAbstractions.git"
SynSrc -orignalDir $rootdir -srcDir "ASPNET/Identity" -projectName "ASPNET/Identity" -git "https://github.com/ASPNET/Identity.git"
SynSrc -orignalDir $rootdir -srcDir "ASPNET/KestrelHttpServer" -projectName "ASPNET/KestrelHttpServer" -git "https://github.com/ASPNET/KestrelHttpServer.git"
SynSrc -orignalDir $rootdir -srcDir "ASPNET/KRuntime" -projectName "ASPNET/KRuntime" -git "https://github.com/ASPNET/KRuntime.git"
SynSrc -orignalDir $rootdir -srcDir "ASPNET/Logging" -projectName "ASPNET/Logging" -git "https://github.com/ASPNET/Logging.git"
SynSrc -orignalDir $rootdir -srcDir "ASPNET/MusicStore" -projectName "ASPNET/MusicStore" -git "https://github.com/ASPNET/MusicStore.git"
SynSrc -orignalDir $rootdir -srcDir "ASPNET/Mvc" -projectName "ASPNET/Mvc" -git "https://github.com/ASPNET/Mvc.git"
SynSrc -orignalDir $rootdir -srcDir "ASPNET/Options" -projectName "ASPNET/Options" -git "https://github.com/ASPNET/Options.git"
SynSrc -orignalDir $rootdir -srcDir "ASPNET/Razor" -projectName "ASPNET/Razor" -git "https://github.com/ASPNET/Razor.git"
SynSrc -orignalDir $rootdir -srcDir "ASPNET/DNX" -projectName "ASPNET/DNX" -git "https://github.com/aspnet/DNX.git"
SynSrc -orignalDir $rootdir -srcDir "ASPNET/Performance" -projectName "ASPNET/Performance" -git "https://github.com/aspnet/Performance.git"
SynSrc -orignalDir $rootdir -srcDir "ASPNET/dnvm" -projectName "ASPNET/dnvm" -git "https://github.com/aspnet/dnvm.git"
#SynSrc -orignalDir $rootdir -srcDir "ASPNET/HttpClient" -projectName "ASPNET/HttpClient" -git "https://github.com/aspnet/HttpClient.git"
SynSrc -orignalDir $rootdir -srcDir "ASPNET/Routing" -projectName "ASPNET/Routing" -git "https://github.com/ASPNET/Routing.git"
SynSrc -orignalDir $rootdir -srcDir "ASPNET/Security" -projectName "ASPNET/Security" -git "https://github.com/ASPNET/Security.git"
SynSrc -orignalDir $rootdir -srcDir "ASPNET/SignalR-Client-Java" -projectName "ASPNET/SignalR-Client-Java" -git "https://github.com/ASPNET/SignalR-Client-Java.git"
SynSrc -orignalDir $rootdir -srcDir "ASPNET/SignalR-Client-JS" -projectName "ASPNET/SignalR-Client-JS" -git "https://github.com/ASPNET/SignalR-Client-JS.git"
SynSrc -orignalDir $rootdir -srcDir "ASPNET/SignalR-Client-Net" -projectName "ASPNET/SignalR-Client-Net" -git "https://github.com/ASPNET/SignalR-Client-Net.git"
SynSrc -orignalDir $rootdir -srcDir "ASPNET/SignalR-Client-Cpp" -projectName "ASPNET/SignalR-Client-Cpp" -git "https://github.com/aspnet/SignalR-Client-Cpp.git"
SynSrc -orignalDir $rootdir -srcDir "ASPNET/SignalR-SqlServer" -projectName "ASPNET/SignalR-SqlServer" -git "https://github.com/ASPNET/SignalR-SqlServer.git"
SynSrc -orignalDir $rootdir -srcDir "ASPNET/SignalR-Redis" -projectName "ASPNET/SignalR-Redis" -git "https://github.com/ASPNET/SignalR-Redis.git"
SynSrc -orignalDir $rootdir -srcDir "ASPNET/SignalR-Server" -projectName "ASPNET/SignalR-Server" -git "https://github.com/ASPNET/SignalR-Server.git"
SynSrc -orignalDir $rootdir -srcDir "ASPNET/SignalR-ServiceBus" -projectName "ASPNET/SignalR-ServiceBus" -git "https://github.com/ASPNET/SignalR-ServiceBus.git"
SynSrc -orignalDir $rootdir -srcDir "ASPNET/StaticFiles" -projectName "ASPNET/StaticFiles" -git "https://github.com/ASPNET/StaticFiles.git"
SynSrc -orignalDir $rootdir -srcDir "ASPNET/Testing" -projectName "ASPNET/Testing" -git "https://github.com/ASPNET/Testing.git"
SynSrc -orignalDir $rootdir -srcDir "ASPNET/Universe" -projectName "ASPNET/Universe" -git "https://github.com/ASPNET/Universe.git"
#SynSrc -orignalDir $rootdir -srcDir "ASPNET/WebSocketAbstractions" -projectName "ASPNET/WebSocketAbstractions" -git "https://github.com/ASPNET/WebSocketAbstractions.git"
SynSrc -orignalDir $rootdir -srcDir "ASPNET/WebSockets" -projectName "ASPNET/WebSockets" -git "https://github.com/ASPNET/WebSockets.git"
SynSrc -orignalDir $rootdir -srcDir "ASPNET/vsweb-docs" -projectName "ASPNET/vsweb-docs" -git "https://github.com/aspnet/vsweb-docs.git"
SynSrc -orignalDir $rootdir -srcDir "ASPNET/aspnet-docker" -projectName "ASPNET/aspnet-docker" -git "https://github.com/aspnet/aspnet-docker.git"
SynSrc -orignalDir $rootdir -srcDir "ASPNET/Session" -projectName "ASPNET/Session" -git "https://github.com/ASPNET/Session.git"
SynSrc -orignalDir $rootdir -srcDir "ASPNET/Docs" -projectName "ASPNET/Docs" -git "https://github.com/ASPNET/Docs.git"
#SynSrc -orignalDir $rootdir -srcDir "ASPNET/aspnet.xunit" -projectName "ASPNET/aspnet.xunit" -git "https://github.com/aspnet/aspnet.xunit.git"
#SynSrc -orignalDir $rootdir -srcDir "ASPNET/xunit" -projectName "ASPNET/xunit" -git "https://github.com/aspnet/xunit.git"
SynSrc -orignalDir $rootdir -srcDir "ASPNET/Common" -projectName "ASPNET/Common" -git "https://github.com/ASPNET/Common.git"
SynSrc -orignalDir $rootdir -srcDir "ASPNET/Scaffolding" -projectName "ASPNET/Scaffolding" -git "https://github.com/ASPNET/Scaffolding.git"
SynSrc -orignalDir $rootdir -srcDir "ASPNET/Signing" -projectName "ASPNET/Signing" -git "https://github.com/ASPNET/Signing.git"
SynSrc -orignalDir $rootdir -srcDir "ASPNET/CORS" -projectName "ASPNET/CORS" -git "https://github.com/ASPNET/CORS.git"
SynSrc -orignalDir $rootdir -srcDir "ASPNET/Tooling" -projectName "ASPNET/Tooling" -git "https://github.com/ASPNET/Tooling.git"
SynSrc -orignalDir $rootdir -srcDir "ASPNET/jquery-ajax-unobtrusive" -projectName "ASPNET/jquery-ajax-unobtrusive" -git "https://github.com/ASPNET/jquery-ajax-unobtrusive.git"
SynSrc -orignalDir $rootdir -srcDir "ASPNET/jquery-validation-unobtrusive" -projectName "ASPNET/jquery-validation-unobtrusive" -git "https://github.com/ASPNET/jquery-validation-unobtrusive.git"
SynSrc -orignalDir $rootdir -srcDir "ASPNET/homebrew-k" -projectName "ASPNET/homebrew-k" -git "https://github.com/ASPNET/homebrew-k.git"

#Write-Host -ForegroundColor Green  "全部完成"




